# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
#default: &default
#  adapter: sqlite3
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000

# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>
  username: <%= ENV.fetch("MYSQL_USER") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "localhost" } %>
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %>

development:
  <<: *default
  #  database: db/development.sqlite3
  database: library_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  #  database: db/test.sqlite3
  database: library_test

production:
  <<: *default
  #  database: db/production.sqlite3
  database: library
  username: root
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "password" } %>
